defaults:
  - scope:
      path: index
    values:
      layout: index
  - scope:
      path: topic
    values:
      layout: topic
  - scope:
      path: week
    values:
      layout: week
livereload: true
sass:
  implementation: sass-embedded
  sass_dir:       assets/styles
  sourcemap:      never
theme: null
